version: '3.8'

services:
  db:
    image: mysql
    container_name: spring_security_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: spring-security-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: